# Generated by Django 6.0.7 on 2026-07-26 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Indian mobile number: 10 digits starting with 6-9, optional +91 or 0 prefix.', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Indian mobile number (10 digits starting with 6-9, optional +91 or 0 prefix).', regex='^(?:\\+91|0)?[6-9]\\d{9}$')]),
        ),
    ]
