"""
Generated by Django 6.0.6

Adds NotificationLog model and new Reminder statuses (TRIGGERED, SNOOZED)
plus recurring fields.
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        # Alter status choices on Reminder (add TRIGGERED, SNOOZED)
        migrations.AlterField(
            model_name="reminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("TRIGGERED", "Triggered"),
                    ("TAKEN", "Taken"),
                    ("MISSED", "Missed"),
                    ("SNOOZED", "Snoozed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        # Add new fields to Reminder
        migrations.AddField(
            model_name="reminder",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reminder",
            name="recurring_interval",
            field=models.CharField(
                blank=True,
                help_text="Daily, Weekly, Monthly",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="snoozed_until",
            field=models.DateTimeField(
                blank=True,
                help_text="If snoozed, the time until which the reminder is snoozed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reminder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        # Create NotificationLog model
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("PUSH", "Push"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True,
                        help_text="Email address, phone number, or device token",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="reminders.reminder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="accounts.User",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["user", "reminder"],
                name="reminders_n_user_id_abc123",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["status"],
                name="reminders_n_status_abc124",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["channel"],
                name="reminders_n_channel_abc125",
            ),
        ),
    ]
