# Generated by Django 6.0.6 on 2026-07-07 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                (
                    "medicine_type",
                    models.CharField(
                        choices=[
                            ("TABLET", "Tablet"),
                            ("CAPSULE", "Capsule"),
                            ("SYRUP", "Syrup"),
                            ("INJECTION", "Injection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dosage", models.CharField(max_length=50)),
                ("frequency", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("instructions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
