# Generated by Django 6.0.7 on 2026-07-14 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
