# Generated by Django 6.0.7 on 2026-08-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_is_active_medicine_reminder_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='frequency_doses_per_day',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 time/day'), (2, '2 times/day'), (3, '3 times/day'), (4, '4 times/day')], default=1, help_text='How many times per day this medicine should be taken (1–4).'),
        ),
    ]
